### ISSUE TITLE
Newly generated project errors with "Non-string value passed to `ts.resolveTypeReferenceDirective`"

### ISSUE THREAD

**Issue by saavyone** [optro-cloud/create-trello-powerup#27]
```$ yarn build
yarn run v1.22.19
$ webpack --config webpack.config.ts --mode=production
[webpack-cli] Failed to load '/Users/msaavedra/code/saavy-powerup/webpack.config.ts' config
[webpack-cli] Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
    at Object.resolveTypeReferenceDirective (/Users/msaavedra/code/saavy-powerup/node_modules/typescript/lib/typescript.js:42537:18)
    at /Users/msaavedra/code/saavy-powerup/node_modules/ts-node/src/index.ts:623:55
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (/Users/msaavedra/code/saavy-powerup/node_modules/ts-node/src/index.ts:622:33)
    at actualResolveTypeReferenceDirectiveNamesWorker (/Users/msaavedra/code/saavy-powerup/node_modules/typescript/lib/typescript.js:116674:163)
    at resolveTypeReferenceDirectiveNamesWorker (/Users/msaavedra/code/saavy-powerup/node_modules/typescript/lib/typescript.js:116974:26)
    at processTypeReferenceDirectives (/Users/msaavedra/code/saavy-powerup/node_modules/typescript/lib/typescript.js:118456:31)
    at findSourceFileWorker (/Users/msaavedra/code/saavy-powerup/node_modules/typescript/lib/typescript.js:118341:21)
    at findSourceFile (/Users/msaavedra/code/saavy-powerup/node_modules/typescript/lib/typescript.js:118196:26)
    at /Users/msaavedra/code/saavy-powerup/node_modules/typescript/lib/typescript.js:118148:85
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by saavyone** [comment]
I resolved it thanks to StackOverflow https://stackoverflow.com/a/72528793/3075663 by simply updating ts-node to 10.8.1

But, you should update the template accordingly
